USE SCHEMA SANJAY_SCHEMA;
-- CREATE TABLE TO LOAD CSV DATA
CREATE OR REPLACE TABLE PRACTICEDB.SANJAY_SCHEMA.HEALTHCARE_CSV(
    AVERAGE_COVERED_CHARGES    NUMBER(38,6)  
   ,AVERAGE_TOTAL_PAYMENTS    NUMBER(38,6)  
   ,TOTAL_DISCHARGES    NUMBER(38,0)  
   ,BACHELORORHIGHER    NUMBER(38,1)  
   ,HSGRADORHIGHER    NUMBER(38,1)  
   ,TOTALPAYMENTS    VARCHAR(128)  
   ,REIMBURSEMENT    VARCHAR(128)  
   ,TOTAL_COVERED_CHARGES    VARCHAR(128) 
   ,REFERRALREGION_PROVIDER_NAME    VARCHAR(256)  
   ,REIMBURSEMENTPERCENTAGE    NUMBER(38,9)  
   ,DRG_DEFINITION    VARCHAR(256)  
   ,REFERRAL_REGION    VARCHAR(26)  
   ,INCOME_PER_CAPITA    NUMBER(38,0)  
   ,MEDIAN_EARNINGSBACHELORS    NUMBER(38,0)  
   ,MEDIAN_EARNINGS_GRADUATE    NUMBER(38,0)  
   ,MEDIAN_EARNINGS_HS_GRAD    NUMBER(38,0)  
   ,MEDIAN_EARNINGSLESS_THAN_HS    NUMBER(38,0)  
   ,MEDIAN_FAMILY_INCOME    NUMBER(38,0)  
   ,NUMBER_OF_RECORDS    NUMBER(38,0)  
   ,POP_25_OVER    NUMBER(38,0)  
   ,PROVIDER_CITY    VARCHAR(128)  
   ,PROVIDER_ID    NUMBER(38,0)  
   ,PROVIDER_NAME    VARCHAR(256)  
   ,PROVIDER_STATE    VARCHAR(128)  
   ,PROVIDER_STREET_ADDRESS    VARCHAR(256)  
   ,PROVIDER_ZIP_CODE    NUMBER(38,0)  
);



-- CREATE FILE FORMAT TO INFORM SNOWFLAKE THAT WHICH FORMAT OF THE FILE TO EXPECT 
CREATE OR REPLACE FILE FORMAT PRACTICEDB.SANJAY_SCHEMA.HEALTHCARE_CSV_FORMAT
TYPE = CSV FIELD_DELIMITER = '|' SKIP_HEADER = 1;
  
-- CREATE STAGE OBJECT TO LET SNOWFLAKE KNOW FROM WHERE TO PICK THE FILES
CREATE OR REPLACE STAGE PRACTICEDB.SANJAY_SCHEMA.HEALTH_STAGE
STORAGE_INTEGRATION = S3_INT
URL = 's3://wav-training/snowflake/health_pipe.csv'
FILE_FORMAT = HEALTHCARE_CSV_FORMAT;

-- TAKE A LOOK AT THE DATA PRIOR TO LOADING INTO THE TABLES
SELECT $1, $5
FROM @PRACTICEDB.SANJAY_SCHEMA.HEALTH_STAGE;
  
-- USE COPY COMMAND TO INGEST DATA FROM AZURE
COPY INTO PRACTICEDB.SANJAY_SCHEMA.HEALTHCARE_CSV
FROM @PRACTICEDB.SANJAY_SCHEMA.HEALTH_STAGE;


-- QUERY TO FETCH DATA DIRECTLY FROM STAGE AREA WITH FILTERS
SELECT AVERAGE_COVERED_CHARGES, AVERAGE_TOTAL_PAYMENTS
FROM PRACTICEDB.SANJAY_SCHEMA.HEALTHCARE_CSV
WHERE $1 < 30000;
